### ISSUE TITLE
can engrave but not cut

### ISSUE THREAD

**Issue by LenoreHorner** [t-oster/VisiCut#481]
If I create text inclosed in an ellipse in Inkscape and use the extension to open that in VisiCut, then if I just engrave the text, things work fine, but if I try to cut around the text or even just cut the ellipse, Visicut just thinks forever.  MacOS never sees it as "not responding" but nothing happens either.  See screen shots.  I tried thinning the ellipse border worried that VisiCut was trying to cut too wide a line but at 0.1mm thickness, I still get hanging.  
![01textwithborder](https://user-images.githubusercontent.com/23015014/46021269-48061200-c0ae-11e8-9ade-e7035a6572d4.png)
![02textwiththinborder](https://user-images.githubusercontent.com/23015014/46021270-48061200-c0ae-11e8-86f4-e20a232a7156.png)
![03borderonly](https://user-images.githubusercontent.com/23015014/46021271-489ea880-c0ae-11e8-8b40-6cea0914204e.png)

**Comment by mgmax** [comment]
Are you using the latest version? Do you get any output when running from the commandline?
In case you don't know how to run from commandline, I just created a wiki article https://github.com/t-oster/VisiCut/wiki/Development:-Running-from-commandline

**Comment by LenoreHorner** [comment]
I made just the outline of an ellipse in Inkscape, started VisiCut from the command line (it's ./VisiCut.MacOS really) and imported the .svg of the ellipse.  I chose 4mm plywood, cut all, and set power and speed according to the Helix manual.  The output I get on the command line follows.
2018-09-25 14:24:45.073 java[9273:2758420] plugin com.adobe.accmac.ACCFinderSync invalidated
Exception in thread "Thread-5" java.lang.NoSuchMethodError: com.t_oster.liblasercut.VectorCommand.getX()I
	at com.t_oster.liblasercut.vectoroptimizers.VectorOptimizer.divide(VectorOptimizer.java:181)
	at com.t_oster.liblasercut.vectoroptimizers.VectorOptimizer.optimize(VectorOptimizer.java:225)
	at com.t_oster.visicut.model.VectorProfile.addToLaserJob(VectorProfile.java:311)
	at com.t_oster.visicut.VisicutModel.prepareJob(VisicutModel.java:766)
	at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:782)
	at com.t_oster.visicut.gui.MainView$65.run(MainView.java:2255)

**Comment by mgmax** [comment]
ah okay, this is bug #479. Can you try downloading the newest version again? Until recently the download had exactly this error, it was replaced by a corrected upload (with the same filename and version number).

**Comment by LenoreHorner** [comment]
I have downloaded the newest version and that does fix the problem.  Thank you.
