### ISSUE TITLE
Exception: A GUI function was called from the non-GUI thread Thread-0

### ISSUE THREAD

**Issue by jnweiger** [t-oster/VisiCut#696]
Seen with today's master
* visicut github tag 886ab0b9
* LibLaserCut tag c2bee3a

Visicut was open, worked fine, was left open, then after several laptop suspend and resume
(and network outages, and reconnects at different WLANs)
an error occured:
```
java.lang.Exception: Warning: A GUI function was called from the non-GUI thread Thread-0. This may cause sporadic errors and should therefore be fixed.
	at de.thomas_oster.visicut.gui.ThreadUtils.assertInGUIThread(ThreadUtils.java:70)
	at de.thomas_oster.visicut.gui.MainView.refreshRecentFilesMenu(MainView.java:506)
	at de.thomas_oster.visicut.gui.MainView.loadFile(MainView.java:1754)
	at de.thomas_oster.visicut.gui.VisicutApp$1.newInstanceCreated(VisicutApp.java:385)
	at de.thomas_oster.visicut.misc.ApplicationInstanceManager.fireNewInstance(ApplicationInstanceManager.java:105)
	at de.thomas_oster.visicut.misc.ApplicationInstanceManager$1.run(ApplicationInstanceManager.java:66)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.Exception: Warning: A GUI function was called from the non-GUI thread Thread-0. This may cause sporadic errors and should therefore be fixed.
	at de.thomas_oster.visicut.gui.ThreadUtils.assertInGUIThread(ThreadUtils.java:70)
	at de.thomas_oster.visicut.gui.MainView.refreshRecentFilesMenu(MainView.java:506)
	at de.thomas_oster.visicut.gui.MainView.loadFile(MainView.java:1754)
	at de.thomas_oster.visicut.gui.VisicutApp$1.newInstanceCreated(VisicutApp.java:385)
	at de.thomas_oster.visicut.misc.ApplicationInstanceManager.fireNewInstance(ApplicationInstanceManager.java:105)
	at de.thomas_oster.visicut.misc.ApplicationInstanceManager$1.run(ApplicationInstanceManager.java:66)
	at java.base/java.lang.Thread.run(Unknown Source)

```
Maybe spoadic and harmless, but may also be an obvious fix for somebody around here?

**Comment by mgmax** [comment]
Fixed. Thanks :-)
